# Generated by Django 2.0.6 on 2018-06-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20180605_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='user_1_age',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='dialog',
            name='user_1_sex',
            field=models.CharField(default='secret', max_length=10),
        ),
        migrations.AddField(
            model_name='dialog',
            name='user_2_age',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='dialog',
            name='user_2_sex',
            field=models.CharField(default='secret', max_length=10),
        ),
    ]
