# Generated by Django 2.0.6 on 2018-06-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20180606_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='user_2_sex',
            field=models.CharField(default='secret', max_length=10),
        ),
    ]
