# Generated by Django 2.0.6 on 2018-06-06 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20180606_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='user_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_2', to='chats.User'),
        ),
    ]
